### PR TITLE
Remove unit field

### PR DESCRIPTION
**Pull request by rvl**
### Overview

Due to uncertainty about how to display tokens with/without metadata present, the `unit` field will be removed.

### Jira ticket

ADP-809

### Comments

- Tested with `git grep -i unit`.
- Tested with registry validation here: input-output-hk/metadata-registry-testnet#80

### CODE REVIEW

**Comment by gitmachtl** [comment]
And the decimal field will be added instead?

**Review by KtorZ — APPROVED** [review]

**Comment by KtorZ** [comment]
> And the decimal field will be added instead?

@gitmachtl Nope, it's gone gone. At least for now in the first release. There's an incoming CIP about token metadata and well known properties. So we'll re-open the discussion in due time on this. For now, the unit field is more of a risk / vulnerability than a must-have feature.

**Comment by AndrewWestberg** [comment]
Can you explain the risk/vulnerability of having a unit field?  Isn't this just fairly simple math that the UI has to do?

**Comment by AndrewWestberg** [comment]
Tokens are ALREADY minted on mainnet assuming a units or decimals field... IOG should figure it out instead of punting on this requirement.  If ada is allowed to have decimals, tokens should be allowed to have decimals.

**Comment by KtorZ** [comment]
@AndrewWestberg two scenarios where having a unit field **as currently specified** would be an issue.

##### Scenario 1

- Alice creates a token "APPLE" and publishes metadata saying the token has 2 decimals. 
- Bob sends Carole 14.42 APPLE 
- Alice changes metadata to 6 decimals.
- Carole now has 0.001442 APPLE 

Imagine how bad this become with automation (e.g. Bob sends a fixed amount of APPLE to Carole every month). 

 ##### Scenario 2
 
 - Alice uses the CF server as a source of metadata. That servers says that "APPLE" coins has 2 decimals.
 - Bob uses a community server hosted by an SPO as a source of metadata. Bob's server says that "APPLE" coin has 6 decimals.
 - Alice now ask Bob to send her 2 APPLE. 
 
 Should Bob sends `2000000` or `200` base units? 
 
---

Those scenarios really are unsound and need further discussion. This is why we are removing this **at this stage**. We'll have this discussion as part of the upcoming CIP proposal. There are several options (on-chain unit, user-defined UI configuration, common convention... ) but we haven't settled on anything. On the other hand, there are already other metadata that would be useful to have now, even if `unit` comes later in the process.

**Comment by AndrewWestberg** [comment]
If people are using different metadata servers and the servers are disagreeing on decimals, isn't that failure on them? If the metadata servers are required to sign the metadata with the same certs that was used in minting, it's ALICE's fault that they are disagreeing on decimals.

**Comment by AndrewWestberg** [comment]
Also, for people doing automation, they can just specify the transaction in APPLETS, SATOSHIs or LOVELACE which is what the underlying protocol is using anyway.

**Comment by rvl** [comment]
You make good points @AndrewWestberg, and I agree.

The ability to decimalize tokens will surely return, as @KtorZ  says.
After deploying token metadata on testnet some concerns about this particular field arose.
We are still working out UI details in Daedalus (especially for hardware wallet support).

You are probably aware -- others may not be -- that token quantities are always whole numbers (this is a good thing), and the `unit` field is purely off-chain metadata. It's simply the name for a bigger unit of the token, _as defined by the minter of the token_.

**Pull request merged**
